apiVersion: apps/v1
kind: Deployment
metadata: {name: nmg-gggg}
spec:
  replicas: 1
  selector:
    matchLabels: {app: nmg-gggg}
  template:
    metadata:
      labels: {app: nmg-gggg}
    spec:
      containers:
      - image: ashspencil/k8s-ml:9.0-cudnn7-devel-ssh-basic
        name: nmg-gggg
        ports:
        - {containerPort: 22, name: ssh}
        resources:
          limits: {memory: 5Gi, nvidia.com/gpu: 0}
          requests: {memory: 2.5Gi}
      nodeSelector: {}
