# Generated by Django 2.1 on 2018-12-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='gpu',
            field=models.CharField(default='+', max_length=20),
        ),
    ]
