# Generated by Django 2.1 on 2018-12-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_deployment_gpu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='gpu',
            new_name='gpu_inuse',
        ),
    ]
