# Generated by Django 2.1 on 2018-09-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_deployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='test',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
