# Generated by Django 2.1 on 2018-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_deployment_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
    ]
