# Generated by Django 2.1 on 2018-12-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_cimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='status',
            new_name='backup',
        ),
    ]
