# Generated by Django 2.1 on 2018-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20181215_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='backup',
            field=models.BooleanField(default=False),
        ),
    ]
